Домашняя работа #3
AfterAlotLies/ShiftHomeWorks pull request #3
Opened 2024-04-26 10:42 UTC by AfterAlotLies

Реализовал следующий функционал приложения:
- Создал UITabBarController 
- Реализовал верстку первого экрана используя Storyboard
- Реализовал нативную верстку остальных экранов 
- На каждом экране 3+ элемента, которые проходили на лекциях
- Реализовал модели для контроллеров
- Разбил на подфункции

2024-04-26 12:46 UTC, rmaximov requested changes

2024-04-26 12:46 UTC, rmaximov commented on HW3/HW3/Controllers/MyHobbiesViewController.swift
> +            introductionLabel.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 16),
константы повторяются много раз, хорошей практикой является их вынос в отдельную сущность

2024-04-26 12:46 UTC, rmaximov commented on HW3/HW3/Controllers/MyHobbiesViewController.swift
> +    private func setupView() {
круто что используешь модификаторы доступа

2024-04-26 12:46 UTC, rmaximov commented on HW3/HW3/Controllers/MyHobbiesViewController.swift
> +        NSLayoutConstraint.activate([
хорошее разделение констрейнтов для активации

2024-04-26 12:46 UTC, rmaximov commented on HW3/HW3/Controllers/MyHobbiesViewController.swift
> +    private func getData() {
название метода говорит о том, что должны вернуться какие-то данные, но само тело метода это установка текстовых значений. Нужно переименовать метод

2024-04-26 12:46 UTC, rmaximov commented on HW3/HW3/Controllers/MyHobbiesViewController.swift
> +    private let scrollViewContainerView: UIStackView = {
почему все остальные элементы lazy, а этот нет?

2024-04-26 12:46 UTC, rmaximov commented on HW3/HW3/Controllers/MyHobbiesViewController.swift
> +        label.font = UIFont.boldSystemFont(ofSize: 25)
как в другом комменте уже писал, повторяющиеся значения лучше выносить во вне
например enum Fonts { ... }

2024-04-26 12:46 UTC, rmaximov commented on HW3/HW3/Models/MyProfileModel.swift
> +enum ProfileModelDescription: String, CaseIterable {
допустимый вариант хранения данных, но enum лучше использовать либо для хранения связанных значений, например enum Colors {}, enum Fruits {}. Но так же может быть использован как контейнер хранения констант. enum позволяет это сделать так и уже набор несвязанных между собой значений
```swift
enum ProfileModelDescription {
   static let age = 20
}
```

А вообще давай подумаем, если нам надо будет изменить какие-то данные или добавить новые, то как лучше построить модель?

2024-04-26 12:46 UTC, rmaximov commented on HW3/HW3/Models/MySkillsModel.swift
> +enum SkillsModel: String {
такой же вопрос как и для ProfileModelDescription

2024-04-26 12:46 UTC, rmaximov commented on HW3/HW3/Controllers/TabBarController.swift
> +        for item in 0...2 {
Если мы изменим количество табов, то иконки для остальных не проставятся?

2024-04-26 12:46 UTC, rmaximov commented on HW3/HW3/Controllers/MyProfileViewController.swift
> +//  ViewController.swift
минор: следи за названием файлов в копирайтах

2024-04-26 12:46 UTC, rmaximov commented on HW3/HW3/Models/MyProfileModel.swift
> +    case age = "- 20 Лет"
форматирование строки прямо в константах не самая удачная практика. Вдруг тебе надо будет сделать перенос строки или использовать тире
поэтому можно оставить age = "20 лет" и в месте где ты устанавливаешь строку, уже производить с ней манипуляции

2024-04-28 11:42 UTC, AfterAlotLies commented on HW3/HW3/Controllers/MyHobbiesViewController.swift
> +    private func getData() {
Исправил

2024-04-28 11:42 UTC, AfterAlotLies commented on HW3/HW3/Controllers/MyHobbiesViewController.swift
> +    private let scrollViewContainerView: UIStackView = {
Ну я читал, что stackView обычно инициализируется при обращению к коду и его можно не делать ленивым т.к. его инициализация сильно не ест ресурсы системы, поэтому его сделал не ленивым

2024-04-28 11:43 UTC, AfterAlotLies commented on HW3/HW3/Controllers/MyHobbiesViewController.swift
> +        label.font = UIFont.boldSystemFont(ofSize: 25)
Исправил

2024-04-28 11:43 UTC, AfterAlotLies commented on HW3/HW3/Models/MyProfileModel.swift
> +enum ProfileModelDescription: String, CaseIterable {
Исправил
В голову пришло только одно разумное изменение хранение данных

2024-04-28 11:43 UTC, AfterAlotLies commented on HW3/HW3/Models/MySkillsModel.swift
> +enum SkillsModel: String {
Исправил

2024-04-28 11:43 UTC, AfterAlotLies commented on HW3/HW3/Controllers/TabBarController.swift
> +        for item in 0...2 {
Исправил

2024-04-28 11:43 UTC, AfterAlotLies commented on HW3/HW3/Controllers/MyProfileViewController.swift
> +//  ViewController.swift
Исправил

2024-04-28 11:43 UTC, AfterAlotLies commented on HW3/HW3/Models/MyProfileModel.swift
> +    case age = "- 20 Лет"
Исправил

2024-04-29 15:03 UTC, rmaximov commented on HW3/HW3/Controllers/MySkillsViewController.swift
> +    private let skillsUIData = SkillsUIData.init(
минор: init можно не писать

2024-04-29 15:07 UTC, rmaximov commented on HW3/HW3/Models/MyProfileModel.swift
> +enum ProfileModelDescription: String, CaseIterable {
и оно верное, с моделькой в виде структуры проще работать

2024-04-30 11:33 UTC, AfterAlotLies commented on HW3/HW3/Controllers/MyHobbiesViewController.swift
> +            introductionLabel.topAnchor.constraint(equalTo: view.safeAreaLayoutGuide.topAnchor, constant: 16),
Исправил

2024-04-30 11:34 UTC, AfterAlotLies commented on HW3/HW3/Controllers/MySkillsViewController.swift
> +    private let skillsUIData = SkillsUIData.init(
Исправил

2024-04-30 12:06 UTC, rmaximov approved these changes
Хорошая работа, замечания учтены. Молодец

2024-04-30 12:57 UTC, merged