Домашние задание #4
AfterAlotLies/ShiftHomeWorks pull request #5
Opened 2024-05-08 13:08 UTC by AfterAlotLies

Реализовал следующий функционал приложения:
- Добавил контроллер с коллекцией, отображающую информацию
- Добавил контроллер с подробной информацией о каждой ячейке коллекции
- Добавил модальный контроллер с доп. информацией
- Реализовал навигацию

2024-05-11 13:52 UTC, rmaximov requested changes
Хорошая работа, есть небольшие недочеты
обрати внимание на сгенерированные init с fatalError, как закрыть доступ к ним
использование self

2024-05-11 13:52 UTC, rmaximov commented on HW4/HW4/Controllers/HeroComplexity/HeroComplexityViewController.swift
> +            gradientLayer.endPoint = CGPoint(x: 0, y: 0)
endPoint не меняется, его можно вынести из switch

2024-05-11 13:52 UTC, rmaximov commented on HW4/HW4/Controllers/HeroesList/HeroesListViewController.swift
> +        heroInfoController.passData(data: heroesMokoData[indexPath.item])
а тут не вылетем за границы массива случайно?

2024-05-11 13:52 UTC, rmaximov commented on HW4/HW4/Views/HeroesCollectionView/HeroesCollectionView.swift
> +protocol HeroesCollectionViewDelegate: UICollectionViewDelegate {
а зачем пустой делегат, который реализует UICollectionViewDelegate?

2024-05-11 13:52 UTC, rmaximov commented on HW4/HW4/HeroesCollectionViewDataSource/HeroesCollectionViewDataSource.swift
> +        return DataManager.createMoko().count
уже же создана переменная mokoData, её можно использовать

2024-05-11 13:52 UTC, rmaximov commented on HW4/HW4/HeroesCollectionViewDataSource/HeroesCollectionViewDataSource.swift
> +    private var mokoData = DataManager.createMoko()
что за moko, може ты mock имел в виду?

2024-05-13 07:20 UTC, AfterAlotLies commented on HW4/HW4/Controllers/HeroComplexity/HeroComplexityViewController.swift
> +            gradientLayer.endPoint = CGPoint(x: 0, y: 0)
Исправил

2024-05-13 07:23 UTC, AfterAlotLies commented on HW4/HW4/Controllers/HeroesList/HeroesListViewController.swift
> +        heroInfoController.passData(data: heroesMokoData[indexPath.item])
Исправил

2024-05-13 07:24 UTC, AfterAlotLies commented on HW4/HW4/Views/HeroesCollectionView/HeroesCollectionView.swift
> +protocol HeroesCollectionViewDelegate: UICollectionViewDelegate {
Мы на практике делали точно так же и я посчитал это нормальным в использовании
Я так понимаю, что за счет него мы прокидываем делегат к коллекции и описываем методы делегата в самом контроллере уже

2024-05-13 07:24 UTC, AfterAlotLies commented on HW4/HW4/HeroesCollectionViewDataSource/HeroesCollectionViewDataSource.swift
> +        return DataManager.createMoko().count
Исправил

2024-05-13 07:24 UTC, AfterAlotLies commented on HW4/HW4/HeroesCollectionViewDataSource/HeroesCollectionViewDataSource.swift
> +    private var mokoData = DataManager.createMoko()
Исправил

2024-05-13 09:19 UTC, rmaximov commented on HW4/HW4/Views/HeroesCollectionView/HeroesCollectionView.swift
> +protocol HeroesCollectionViewDelegate: UICollectionViewDelegate {
на практике может не успели реализовать методы, но если у тебя твой делегат пустой, то проще отказаться от него. Меньше сущностей - проще код

2024-05-13 09:20 UTC, rmaximov approved these changes

2024-05-13 09:48 UTC, merged