Домашнее задание #5
AfterAlotLies/ShiftHomeWorks pull request #6
Opened 2024-05-19 14:23 UTC by AfterAlotLies

Реализовал следующий функционал: 
- Реализовал 1-й экран по архитектуре MVC
- Реализовал 2-й экран по архитектуре MVP
- Реализовал 3-й экран по архитектуре MVVM + добавил изменение данных в рандомный промежуток времени на этом экране

2024-05-23 07:03 UTC, AlexRaptor commented on HW5/HW5/Resources/Enums/Colors.swift
> +    static let whiteColor: UIColor = .white
Не по теме работы, но замечу: не нужно называть "белыйЦвет", зачем в таком случае перечисление?
Вот представь ситуацию: тебе нужно, что бы здесь был красный. Тебе придётся:
1. Внести изменения в `... = .red`
2. Переименовать элемент энама в `redColor`
3. Пройти по всему коду и внести изменения, где этот элемент использовался

Правильнее называть как-нить так primaryColor, secondaryColor или textColor, backgroundColor - т.е. плясать не от реализации, а от назначения.

Тоже самое и про шрифты: должно быть что-то типа Font.Title, Font.SubtitleBold

2024-05-23 07:10 UTC, AlexRaptor commented on HW5/HW5/HeroesListScreen/Controller/HeroesListViewController.swift
> +        for heroesMockDatum in heroesMockData {
для этого есть `map` 
переделай

2024-05-23 07:13 UTC, AlexRaptor commented on HW5/HW5/HeroesListScreen/View/HeroesCollectionViewDataSource/HeroesCollectionViewDataSource.swift
> +     var mockData = [HeroesCollectionModel]()
1. Не хорошее именование - дата-сорсу по барабану, это мок данных, или они настоящие. Так получается, что дата-сорс у тебя знает о реализации
2. Дата-сорс опять же знает о реализации вью - т.к. хранит данные о модели уровня вью `HeroesCollectionModel`. Он должен хранить более "сырые данные" своего уровня

2024-05-23 07:15 UTC, AlexRaptor commented on HW5/HW5/HeroesListScreen/Controller/HeroesListViewController.swift
> +        view.dataSource.mockData = convertDataModel(data: heroesMockData)
Не должен вью-контроллер сетить данные в дата-сорс. Дата-сорс сам должен сходить в манагер и взять данные

2024-05-23 07:16 UTC, AlexRaptor commented on HW5/HW5/HeroesListScreen/Controller/HeroesListViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
Тут у метода получилось 2 ответственности:
1. Собрать модуль
2. Навигироваться

Раздели по разным методам

2024-05-23 07:22 UTC, AlexRaptor commented on HW5/HW5/HeroInfoScreen/View/HeroInformationViewController.swift
> +        heroInfoView.setAction { [weak self] in
Название метода и то, что он делает, не совпадают

2024-05-23 07:26 UTC, AlexRaptor commented on HW5/HW5/HeroInfoScreen/View/HeroInformationViewController.swift
> +    override func viewWillLayoutSubviews() {
Смотри, это - презентационная логика. Вью-контроллер должен служить только прослойкой между вью и презентером. Тут нужно поступить как с `viewDidLoad` - сказать презентеру, что наступило такое событие, а он уже должен подёргать методы перестройки вью

2024-05-23 07:27 UTC, AlexRaptor commented on HW5/HW5/HeroInfoScreen/View/HeroInformationViewController.swift
> +    override func viewWillLayoutSubviews() {
и здесь точно супер дёрнуть не нужно?

2024-05-23 07:28 UTC, AlexRaptor commented on HW5/HW5/HeroInfoScreen/View/HeroInformationView.swift
> +        static let agilityImage: UIImage? = UIImage(named: "image1")
Это тоже можно было бы вынести в энамы

2024-05-23 07:29 UTC, AlexRaptor commented on HW5/HW5/HeroInfoScreen/Presenter/Presenter.swift
> +    private var heroInfo: HeroesListModel
Выглядит как константа

2024-05-23 07:46 UTC, AlexRaptor commented on HW5/HW5/HeroComplexityScreen/View/HeroComplexityViewController.swift
> +        static let firstYcolor = UIColor(red: 84.0 / 255.0, green: 13.0 / 255.0, blue: 13.0 / 255.0, alpha: 1)
У тебя это в каждом контроллере есть. Это же цвета - вынеси в энам.
Можно по отдельности положить, а можно вообще массивом, для использования в градиенте

2024-05-23 07:49 UTC, AlexRaptor commented on HW5/HW5/HeroComplexityScreen/ViewModel/ViewModel.swift
> +        setupRandomTimer()
А зечем ты это дёргаешь ещё один раз, у тебя же в таймере репит = тру?

2024-05-23 07:50 UTC, AlexRaptor commented on HW5/HW5/HeroComplexityScreen/ViewModel/ViewModel.swift
> +protocol IViewModel: AnyObject {
Название протокола говорит о том, что это протокол вью-модели, а на самом деле - нет

2024-05-23 07:50 UTC, AlexRaptor commented on HW5/HW5/HeroComplexityScreen/View/HeroComplexityViewController.swift
> +extension HeroComplexityViewController: IViewModel {
Контроллер - не вьюМодель, он - вью

2024-05-23 07:53 UTC, AlexRaptor requested changes
Поправь, пожалуйста, замечания

2024-05-24 12:11 UTC, AfterAlotLies commented on HW5/HW5/Resources/Enums/Colors.swift
> +    static let whiteColor: UIColor = .white
Исправил

2024-05-24 12:11 UTC, AfterAlotLies commented on HW5/HW5/HeroesListScreen/Controller/HeroesListViewController.swift
> +        for heroesMockDatum in heroesMockData {
Исправил

2024-05-24 12:12 UTC, AfterAlotLies commented on HW5/HW5/HeroesListScreen/View/HeroesCollectionViewDataSource/HeroesCollectionViewDataSource.swift
> +     var mockData = [HeroesCollectionModel]()
Исправил

2024-05-24 12:12 UTC, AfterAlotLies commented on HW5/HW5/HeroesListScreen/Controller/HeroesListViewController.swift
> +        view.dataSource.mockData = convertDataModel(data: heroesMockData)
Исправил

2024-05-24 12:12 UTC, AfterAlotLies commented on HW5/HW5/HeroesListScreen/Controller/HeroesListViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
Исправил

2024-05-24 12:12 UTC, AfterAlotLies commented on HW5/HW5/HeroInfoScreen/View/HeroInformationViewController.swift
> +        heroInfoView.setAction { [weak self] in
Исправил

2024-05-24 12:12 UTC, AfterAlotLies commented on HW5/HW5/HeroInfoScreen/View/HeroInformationViewController.swift
> +    override func viewWillLayoutSubviews() {
Исправил

2024-05-24 12:12 UTC, AfterAlotLies commented on HW5/HW5/HeroInfoScreen/Presenter/Presenter.swift
> +    private var heroInfo: HeroesListModel
Исправил

2024-05-24 12:13 UTC, AfterAlotLies commented on HW5/HW5/HeroComplexityScreen/View/HeroComplexityViewController.swift
> +        static let firstYcolor = UIColor(red: 84.0 / 255.0, green: 13.0 / 255.0, blue: 13.0 / 255.0, alpha: 1)
Исправил

2024-05-24 12:13 UTC, AfterAlotLies commented on HW5/HW5/HeroComplexityScreen/ViewModel/ViewModel.swift
> +        setupRandomTimer()
Случайно видимо запихнул туда его, исправил

2024-05-24 12:13 UTC, AfterAlotLies commented on HW5/HW5/HeroComplexityScreen/ViewModel/ViewModel.swift
> +protocol IViewModel: AnyObject {
Исправил

2024-05-24 12:13 UTC, AfterAlotLies commented on HW5/HW5/HeroComplexityScreen/View/HeroComplexityViewController.swift
> +extension HeroComplexityViewController: IViewModel {
Исправил

2024-05-24 12:15 UTC, AfterAlotLies commented on HW5/HW5/HeroInfoScreen/View/HeroInformationView.swift
> +        static let agilityImage: UIImage? = UIImage(named: "image1")
На мой взгляд, намного удобнее находится в одном файле/классе и видеть какие константы относятся к этому файлу/классу, чем выносить это все в разные файлы и потом искать какие из констант к чему относятся, а так, сразу в этом же классе видно, что потребуется исправлять при необходимости

2024-05-28 14:05 UTC, AlexRaptor commented on HW5/HW5/Resources/Enums/Colors.swift
> +    static let labelsTextColor: UIColor = .white
У тебя enum называется `Colors`, не нужно в названии его элементов ещё `Color` подклеивать.

2024-05-28 14:06 UTC, AlexRaptor commented on HW5/HW5/Resources/Enums/Colors.swift
> +    static let labelsTextColor: UIColor = .white
Кстати enum-ы принято называть в единственном числе

2024-05-28 14:10 UTC, AlexRaptor commented on HW5/HW5/HeroesListScreen/Controller/HeroesListViewController.swift
> +    func collectionView(_ collectionView: UICollectionView, didSelectItemAt indexPath: IndexPath) {
Ну, я надеялся, что ты создание модуля вынесешь в метод, а не пуш :) но ладно, править не нужно, думаю ты понял

2024-05-28 14:14 UTC, AlexRaptor commented on HW5/HW5/HeroInfoScreen/View/HeroInformationView.swift
> +        static let agilityImage: UIImage? = UIImage(named: "image1")
Это да, я согласен. Имел ввиду, что если картинки одинаковые используются на разных экранах, например иконки какие-нить, то их бы выносить. Тем более если одну и ту же картинку  держать в сотне файлов/классов, то и памяти занимать она будет как сотня таких картинок

2024-05-28 14:20 UTC, AlexRaptor approved these changes
Можно мержить, есть пара незначительных замечаний, просто прими к сведению :) И ещё по поводу констант, можно делать так:
```swift
enum Color {
    enum Text {
        static let primaryTitle = UIColor.black
        ...
    }

    enum Background {
        static let primary = UIColor.gray
        ...
    }
}
```
И тогда можно так дёргать
```swift
view.background = Color.Background.primary
```

2024-05-28 14:43 UTC, merged