Домашняя работа #6
AfterAlotLies/ShiftHomeWorks pull request #7
Opened 2024-05-28 10:03 UTC by AfterAlotLies

Реализовал следующий функционал приложения%
- Реализовал первый экран на MVP
- Реализовал второй экран на MVP
- Реализовал эмуляцию загрузки данных

2024-06-01 06:26 UTC, AlexRaptor commented on HW6/HW6/CarListScreen/View/CarListViewController.swift
> +        carListPresenter.fetchData(controller: self)
не должен ВК говорить презентеру, что делать

2024-06-01 06:27 UTC, AlexRaptor commented on HW6/HW6/CarListScreen/Presenter/CarListPresenter.swift
> +    private weak var controller: ICarListViewController?
нету в MVP такой сущности как `ViewController`

2024-06-01 06:28 UTC, AlexRaptor commented on HW6/HW6/CarListScreen/View/CarListViewController.swift
> +        dataSource.getCarInfo(carInfo: dataModel)
вью-контроллер относится ко слою view, и не должен командовать моделью. Этим в MVP занимается презентер

2024-06-01 06:29 UTC, AlexRaptor commented on HW6/HW6/CarListScreen/View/CarListViewController.swift
> +        carListView.reloadTableViewData()
и даже команду обновить вью должен дать презентер

2024-06-01 06:33 UTC, AlexRaptor commented on HW6/HW6/CarInfoScreen/View/CarInfoViewController.swift
> +        startLoaderActivity()
этот метод должен быть не в ВК

2024-06-01 06:34 UTC, AlexRaptor commented on HW6/HW6/CarInfoScreen/View/CarInfoViewController.swift
> +        startLoaderActivity()
весь simulateDataLoading
а ещё мне не нравится, что тут зашито знание о том, что загрузка не настоящая, а симулируется. Это знание должно остаться на уровне дата-слоя

2024-06-01 06:35 UTC, AlexRaptor requested changes
ВК не должен содержать логики
И задание не соответствует дизайну из ТЗ

2024-06-02 08:41 UTC, AfterAlotLies commented on HW6/HW6/CarListScreen/View/CarListViewController.swift
> +        carListPresenter.fetchData(controller: self)
Исправил

2024-06-02 08:41 UTC, AfterAlotLies commented on HW6/HW6/CarListScreen/Presenter/CarListPresenter.swift
> +    private weak var controller: ICarListViewController?
Исправил

2024-06-02 08:41 UTC, AfterAlotLies commented on HW6/HW6/CarListScreen/View/CarListViewController.swift
> +        dataSource.getCarInfo(carInfo: dataModel)
Исправил

2024-06-02 08:41 UTC, AfterAlotLies commented on HW6/HW6/CarListScreen/View/CarListViewController.swift
> +        carListView.reloadTableViewData()
Исправил

2024-06-02 08:41 UTC, AfterAlotLies commented on HW6/HW6/CarInfoScreen/View/CarInfoViewController.swift
> +        startLoaderActivity()
Исправил

2024-06-03 14:20 UTC, AlexRaptor commented on HW6/HW6/CarListScreen/Presenter/CarListPresenter.swift
> +    func didLoad(ui: ICarListViewController)
Протокол бы тоже переименовать не мешало, он же в разрезе MVP описывает контракт для View

2024-06-03 14:24 UTC, AlexRaptor commented on HW6/HW6/CarInfoScreen/View/CarInfoViewController.swift
> +        DispatchQueue.main.asyncAfter(deadline: .now() + 2) { [weak self] in
читерство это, а не загрузка

2024-06-03 14:27 UTC, AlexRaptor approved these changes
Можно мержить. Но с крутилятором осталось читерство. Вот будет у тебя боевое приложение, где у тебя будет ожидание? В запросе данных. Т.е. должно быть так:

1. презентер говорит вьюшке запустить крутилятор
2. презентер запускает загрузку данных
3. когда приходят данные (в нашем случае с задержкой), презентер останавливает крутилятор

2024-06-05 10:19 UTC, merged