Домашняя работа #7
AfterAlotLies/ShiftHomeWorks pull request #8
Opened 2024-06-03 09:56 UTC by AfterAlotLies

Реализовал следующий функционал приложения:
- Использование URLSession для запросов в сеть
- Поиск собаки по введенному слову в TextField (Набор слов для проверки: 1. Boxer 2. Hound 3. Dingo 4. Akita 5. Chow)
- Добавление полученной картинки в таблицу
- Загрузка в background 
- Отображение пользователю ошибки с помощью alert message
Используемый api - https://dog.ceo/dog-api/breeds-list

2024-06-03 14:12 UTC, rmaximov commented
![Simulator Screenshot - iPhone SE (3rd generation) - 2024-06-03 at 17 11 33](https://github.com/AfterAlotLies/ShiftHomeWorks/assets/3064057/56c03242-dcd6-4140-9114-e580e586ff80)

Не получается скрыть клавиатуру
Картинки разъехались

2024-06-03 14:32 UTC, rmaximov requested changes
Обрати внимание на интерфейс, скрытие клавиатуры, показ картинок
По остальным - работа с отсутствующими значениями, подумай когда стоит разворачивать опционала, а когда нет и сегрегация протоколов

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/Model/NetworkManager/DataManager.swift
> +        return ""
возвращать, думаю лучше в catch блокер и можно переделать тип на Result

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +    func makeRequest(url: String, completion: @escaping (Result<Data,Error>) -> Void)
мы же не url передаем, а строковый запрос

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +    var backgroundSession: URLSession!
уверен, что force unwrap безопасно?

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +    static let shared = NetworkManager()
я так понимаю ты синглтон хотел сделать? тогда нужно инит приватным сделать

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +    var completionHandlers: [String: (Result<Data, Error>) -> Void] = [:]
все эти поля должны торчать наружу?

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +            print("Incorrect URL")
вижу что ты сделал completion с ошибкой, почему бы его не использовать
да и вообще убрать print везде

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +            if let completionHandler = (UIApplication.shared.delegate as? AppDelegate)?.backgroundSessionCompletionHandler {
нарушение ответственности, лучше ничего не хранить в appdelegate, а сделать отдельную сущность

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +        completionHandlers[task.taskDescription ?? ""] = handler
нужно ли писать completionHandlers, если task.taskDescription nil?

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +        if receivedData[taskDescription] == nil {
тогда уже можно  через if let развернуть

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/Presenter/MainPresenter.swift
> +        networkManager.makeRequest(url: "https://dog.ceo/api/breed/\(findDog)/images/random") { [weak self] result in
презентеру лучше не знать, что есть какой-то endpoint, а просто при запросе передавать параметр

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/View/MainView/MainTableViewCell/MainTableViewCell.swift
> +    func setImage(image: UIImage) {
миноре setImage(_ image...)

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/View/MainView/MainView.swift
> +        NSLayoutConstraint.activate([
константы хорошо бы вынести

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/View/MainView/MainView.swift
> +            return ""
я что-то не уверен, что тут надо возвращать пустую строку

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/View/MainView/MainTableViewDataSource/MainTableViewDataSource.swift
> +protocol IMainTableViewDataSource: UITableViewDataSource {
раздели на протокола UITableViewDataSource и DataProvider (как-то так) в котором будет func addNewImage(imageData: Data)

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/View/MainView/MainView.swift
> +        NSLayoutConstraint.activate([
константы хорошо бы вынести

2024-06-03 14:32 UTC, rmaximov commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +         if let error = error {
тут что-то появилась пирамида ужаса, попробуй разделить как-то

2024-06-05 10:08 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/Model/NetworkManager/DataManager.swift
> +        return ""
Исправил

2024-06-05 10:08 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +    func makeRequest(url: String, completion: @escaping (Result<Data,Error>) -> Void)
Исправил

2024-06-05 10:08 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +    var backgroundSession: URLSession!
Исправил

2024-06-05 10:08 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +    static let shared = NetworkManager()
Исправил

2024-06-05 10:08 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +    var completionHandlers: [String: (Result<Data, Error>) -> Void] = [:]
Исправил

2024-06-05 10:08 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +            print("Incorrect URL")
Исправил

2024-06-05 10:10 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +            if let completionHandler = (UIApplication.shared.delegate as? AppDelegate)?.backgroundSessionCompletionHandler {
Вот тут у меня возникли проблемы
Я создал отдельную сущность, сгрузил в нее все необходимые инструменты для работы, и уже поправил в нетворк сервисе это все, но он даже отказался почему то загружать картинку в открытом приложении, а при свернутом состоянии, он выбрасывает исключение на делегат. Не получилось исправить

2024-06-05 10:10 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +        completionHandlers[task.taskDescription ?? ""] = handler
Исправил

2024-06-05 10:10 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +        if receivedData[taskDescription] == nil {
Исправил

2024-06-05 10:10 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/Presenter/MainPresenter.swift
> +        networkManager.makeRequest(url: "https://dog.ceo/api/breed/\(findDog)/images/random") { [weak self] result in
Исправил

2024-06-05 10:10 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/View/MainView/MainTableViewCell/MainTableViewCell.swift
> +    func setImage(image: UIImage) {
Исправил

2024-06-05 10:10 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/View/MainView/MainView.swift
> +        NSLayoutConstraint.activate([
Исправил

2024-06-05 10:10 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/View/MainView/MainView.swift
> +            return ""
Исправил

2024-06-05 10:11 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/View/MainView/MainTableViewDataSource/MainTableViewDataSource.swift
> +protocol IMainTableViewDataSource: UITableViewDataSource {
Исправил

2024-06-05 10:11 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/View/MainView/MainView.swift
> +        NSLayoutConstraint.activate([
Исправил

2024-06-05 10:11 UTC, AfterAlotLies commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +         if let error = error {
Исправил

2024-06-05 14:35 UTC, rmaximov requested changes

2024-06-05 14:35 UTC, rmaximov commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +                print("error")
а здесь принт остался

2024-06-05 14:35 UTC, rmaximov commented on HW7/HW7/MainScreen/Model/NetworkManager/NetworkManager.swift
> +            if let completionHandler = (UIApplication.shared.delegate as? AppDelegate)?.backgroundSessionCompletionHandler {
а ты проверил - сущность была жива в памяти?

2024-06-07 12:46 UTC, rmaximov approved these changes

2024-06-07 15:54 UTC, merged